from typing import List, Tuple
import numpy as np
from scipy.optimize import linprog


Point = Tuple[float, float]
def _y_on_line(x, x1, y1, x2, y2):
    t = (x - x1) / (x2 - x1)
    return y1 + t * (y2 - y1)
def _feasible_fixed_endpoints(pts: List[Point], i: int, j: int, eps: float) -> bool:
    x1, y1 = pts[i]; x2, y2 = pts[j]
    if x2 == x1:  # should not happen with strictly increasing x
        return False
    for k in range(i + 1, j):
        xk, yk = pts[k]
        yhat = _y_on_line(xk, x1, y1, x2, y2)
        if abs(yk - yhat) > eps:
            return False
    return True
def shortest_path_dp(pc_linear_fx: List[Point], epsilon: float):
    pts = pc_linear_fx
    n = len(pts) - 1
    # Build visibility list nexts[i] = {j>i | segment i->j feasible}
    nexts = [[] for _ in range(n + 1)]
    for i in range(n):
        j = i + 1
        while j <= n and _feasible_fixed_endpoints(pts, i, j, epsilon):
            nexts[i].append(j)
            j += 1

    # Shortest path on DAG
    INF = 10**9
    dp = [INF] * (n + 1)
    prev = [-1] * (n + 1)
    dp[0] = 0
    for i in range(n):
        if dp[i] == INF:
            continue
        for j in nexts[i]:
            if dp[i] + 1 < dp[j]:
                dp[j] = dp[i] + 1
                prev[j] = i

    # Reconstruct
    if dp[n] == INF:
        raise RuntimeError("No feasible simplification within epsilon.")
    idx = []
    cur = n
    while cur != -1:
        idx.append(cur)
        cur = prev[cur]
    idx.reverse()

    optimal_pc = [pts[k] for k in idx]
    optimal_num_pieces = len(optimal_pc) - 1
    given_num_pieces = n
    return optimal_pc, optimal_num_pieces, given_num_pieces



def get_end_interval(i, j, points, epsilon, lo_start, hi_start):
    """
    Compute the feasible interval for y_j' for the segment from i to j,
    with y_i' constrained to [lo_start, hi_start].
    Returns (lo_end, hi_end) or (None, None) if infeasible.
    """
    if i >= j:
        return None, None

    x_list = [p[0] for p in points]
    y_list = [p[1] for p in points]

    dx = x_list[j] - x_list[i]
    if dx == 0:
        return None, None  # degenerate

    num_k = j - i + 1
    num_cons_base = 2 * num_k
    num_cons = num_cons_base + 2  # + bounds on y_start

    A_ub = np.zeros((num_cons, 2))
    b_ub = np.zeros(num_cons)

    cons_idx = 0
    for kk in range(i, j + 1):
        t = 0.0 if kk == i else (x_list[kk] - x_list[i]) / dx
        # upper: (1-t)*y_start + t*y_end <= y_kk + epsilon
        A_ub[cons_idx, 0] = 1 - t
        A_ub[cons_idx, 1] = t
        b_ub[cons_idx] = y_list[kk] + epsilon
        cons_idx += 1
        # lower: -(1-t)*y_start - t*y_end <= -(y_kk - epsilon)
        A_ub[cons_idx, 0] = -(1 - t)
        A_ub[cons_idx, 1] = -t
        b_ub[cons_idx] = -(y_list[kk] - epsilon)
        cons_idx += 1

    # bound y_start <= hi_start
    A_ub[cons_idx, 0] = 1.0
    A_ub[cons_idx, 1] = 0.0
    b_ub[cons_idx] = hi_start
    cons_idx += 1
    # bound -y_start <= -lo_start
    A_ub[cons_idx, 0] = -1.0
    A_ub[cons_idx, 1] = 0.0
    b_ub[cons_idx] = -lo_start

    # Check feasibility
    c_feas = np.array([0.0, 0.0])
    res_feas = linprog(c_feas, A_ub=A_ub, b_ub=b_ub, bounds=(None, None), method='highs')
    if not res_feas.success:
        return None, None

    # Min y_end
    c_min = np.array([0.0, 1.0])
    res_min = linprog(c_min, A_ub=A_ub, b_ub=b_ub, bounds=(None, None), method='highs')
    if not res_min.success:
        return None, None
    lo_end = res_min.fun

    # Max y_end = -min (-y_end)
    c_max = np.array([0.0, -1.0])
    res_max = linprog(c_max, A_ub=A_ub, b_ub=b_ub, bounds=(None, None), method='highs')
    if not res_max.success:
        return None, None
    hi_end = -res_max.fun

    if lo_end > hi_end + 1e-10:  # numerical tolerance
        return None, None

    return lo_end, hi_end

#generated by Grok 4 Fast on 29 Sept 12:40PM
#uses DP LP approach
def fixed_knot_LP(pc_linear_fx, epsilon):
    """
    Computes the optimal piecewise linear approximation with minimal number of pieces
    such that the maximum vertical deviation (infinity norm) is at most epsilon.

    Args:
    pc_linear_fx (list of tuples): List of (x, y) points defining the original piecewise linear function.
                                   Assumes x values are strictly increasing.
    epsilon (float): Tolerance for the infinity norm error.

    Returns:
    tuple: (optimal_pc_linear_fx, optimal_num_pieces, given_num_pieces)
           - optimal_pc_linear_fx: List of (x, y) points for the approximation.
           - optimal_num_pieces: Number of pieces in the approximation.
           - given_num_pieces: Number of pieces in the input.
    """
    points = pc_linear_fx
    m = len(points)
    if m < 2:
        return points, 0, 0

    given_num_pieces = m - 1

    x_list = [p[0] for p in points]
    y_list = [p[1] for p in points]

    INF = float('inf')
    dp = [INF] * m
    prev = [-1] * m
    lo_y = [0.0] * m
    hi_y = [0.0] * m

    dp[0] = 0
    lo_y[0] = y_list[0] - epsilon
    hi_y[0] = y_list[0] + epsilon

    for j in range(1, m):
        min_cost = INF
        union_lo = INF
        union_hi = -INF
        best_prev = -1

        for i in range(j):
            if dp[i] == INF:
                continue
            lo_end, hi_end = get_end_interval(i, j, points, epsilon, lo_y[i], hi_y[i])
            if lo_end is None:
                continue

            new_cost = dp[i] + 1
            if new_cost < min_cost:
                min_cost = new_cost
                union_lo = lo_end
                union_hi = hi_end
                best_prev = i
            elif new_cost == min_cost:
                union_lo = min(union_lo, lo_end)
                union_hi = max(union_hi, hi_end)
                # best_prev remains the same

        if min_cost < INF:
            dp[j] = min_cost
            lo_y[j] = union_lo
            hi_y[j] = union_hi
            prev[j] = best_prev

    optimal_num_pieces = int(dp[m - 1]) if dp[m - 1] < INF else given_num_pieces

    # Reconstruct kept indices
    kept = []
    current = m - 1
    while current >= 0:
        kept.append(current)
        if prev[current] == -1:
            break
        current = prev[current]
    kept.reverse()

    # Now solve global LP for y_primes
    num_kept = len(kept)
    if num_kept == 1:
        # Only one point
        y_prime = [y_list[kept[0]]]  # but adjust? but no segments
        optimal_pc_linear_fx = [(x_list[kept[0]], y_list[kept[0]])]
    else:
        num_pieces = num_kept - 1
        num_constraints = 0
        for r in range(num_pieces):
            a = kept[r]
            b = kept[r + 1]
            num_k = b - a + 1
            num_constraints += 2 * num_k

        A_ub_list = []
        b_ub_list = []

        for r in range(num_pieces):
            a = kept[r]
            b = kept[r + 1]
            dx = x_list[b] - x_list[a]
            if dx == 0:
                # degenerate, but skip or handle
                continue
            for kk in range(a, b + 1):
                t = 0.0 if kk == a else (x_list[kk] - x_list[a]) / dx
                # upper
                row = np.zeros(num_kept)
                row[r] = 1 - t
                row[r + 1] = t
                A_ub_list.append(row)
                b_ub_list.append(y_list[kk] + epsilon)
                # lower
                row = np.zeros(num_kept)
                row[r] = -(1 - t)
                row[r + 1] = -t
                A_ub_list.append(row)
                b_ub_list.append(-(y_list[kk] - epsilon))

        if len(A_ub_list) == 0:
            optimal_pc_linear_fx = [(x_list[idx], y_list[idx]) for idx in kept]
        else:
            A_ub = np.vstack(A_ub_list)
            b_ub = np.array(b_ub_list)
            c = np.zeros(num_kept)
            res = linprog(c, A_ub=A_ub, b_ub=b_ub, bounds=(None, None), method='highs')
            if res.success:
                y_primes = res.x
                optimal_pc_linear_fx = [(x_list[idx], y_primes[p]) for p, idx in enumerate(kept)]
            else:
                # Fallback to original if somehow infeasible
                optimal_pc_linear_fx = points
                optimal_num_pieces = given_num_pieces

    return optimal_pc_linear_fx, optimal_num_pieces, given_num_pieces


def compute_min_E_and_fit(i, j, points):
    """Compute minimax (Chebyshev) fit and minimum E for points[i:j+1]."""
    if j - i < 1:
        return 0.0, None, None
    x = np.array([p[0] for p in points[i:j+1]])
    y = np.array([p[1] for p in points[i:j+1]])
    n = j - i + 1
    A_ub = np.zeros((2*n, 3))
    b_ub = np.zeros(2*n)
    for k in range(n):
        # a * x_k + b - E <= y_k
        A_ub[2*k, 0] = x[k]
        A_ub[2*k, 1] = 1.0
        A_ub[2*k, 2] = -1.0
        b_ub[2*k] = y[k]
        # -a * x_k - b - E <= -y_k
        A_ub[2*k+1, 0] = -x[k]
        A_ub[2*k+1, 1] = -1.0
        A_ub[2*k+1, 2] = -1.0
        b_ub[2*k+1] = -y[k]
    c = np.array([0.0, 0.0, 1.0])
    res = linprog(c, A_ub=A_ub, b_ub=b_ub, bounds=(None, None), method='highs')
    if res.success:
        return res.fun, res.x[0], res.x[1]
    else:
        return float('inf'), None, None

def reconstruct_optimal_points(points, kept, epsilon):
    """Reconstruct the optimal piecewise linear function from kept indices."""
    x_list = [p[0] for p in points]
    y_list = [p[1] for p in points]
    num_kept = len(kept)
    if num_kept < 2:
        return [(x_list[kept[0]], y_list[kept[0]])] if num_kept == 1 else [], 0
    num_pieces = num_kept - 1
    A_ub_list = []
    b_ub_list = []
    for r in range(num_pieces):
        a = kept[r]
        b = kept[r + 1]
        dx = x_list[b] - x_list[a]
        if dx == 0:
            continue
        for kk in range(a, b + 1):
            t = 0.0 if kk == a else (x_list[kk] - x_list[a]) / dx
            # upper: (1-t)*y_a + t*y_b <= y_kk + epsilon
            row = np.zeros(num_kept)
            row[r] = 1 - t
            row[r + 1] = t
            A_ub_list.append(row)
            b_ub_list.append(y_list[kk] + epsilon)
            # lower: -(1-t)*y_a - t*y_b <= -(y_kk - epsilon)
            row = np.zeros(num_kept)
            row[r] = -(1 - t)
            row[r + 1] = -t
            A_ub_list.append(row)
            b_ub_list.append(-(y_list[kk] - epsilon))
    if not A_ub_list:
        return [(x_list[idx], y_list[idx]) for idx in kept]
    A_ub = np.vstack(A_ub_list)
    b_ub = np.array(b_ub_list)
    c = np.zeros(num_kept)
    res = linprog(c, A_ub=A_ub, b_ub=b_ub, bounds=(None, None), method='highs')
    if res.success:
        y_primes = res.x
        return [(x_list[idx], y_primes[p]) for p, idx in enumerate(kept)]
    else:
        return points


def greedy_farthest(pc_linear_fx, epsilon):
    """Greedy Farthest with Minimax Check"""
    points = pc_linear_fx
    m = len(points)
    if m < 2:
        return points, 0, 0
    given_num_pieces = m - 1
    kept = [0]
    current = 0
    while current < m - 1:
        found = False
        for j in range(m - 1, current, -1):
            min_E, _, _ = compute_min_E_and_fit(current, j, points)
            if min_E <= epsilon:
                kept.append(j)
                current = j
                found = True
                break
        if not found:
            kept.append(m - 1)
            break
    optimal_pc_linear_fx = reconstruct_optimal_points(points, kept, epsilon)
    optimal_num_pieces = len(optimal_pc_linear_fx) - 1 if len(optimal_pc_linear_fx) > 1 else 0
    if len(optimal_pc_linear_fx) != len(kept):
        optimal_pc_linear_fx = points
        optimal_num_pieces = given_num_pieces
    return optimal_pc_linear_fx, optimal_num_pieces, given_num_pieces


def recursive_keep_minimax(i, j, points, epsilon):
    """Recursive function for top-down splitting with minimax check."""
    if i >= j:
        return []
    if i + 1 == j:
        return [i, j]
    min_E, a, b = compute_min_E_and_fit(i, j, points)
    if min_E <= epsilon:
        return [i, j]
    x = np.array([p[0] for p in points[i:j+1]])
    y = np.array([p[1] for p in points[i:j+1]])
    pred = a * x + b
    devs = np.abs(y - pred)
    k = i + 1 + np.argmax(devs[1:-1])
    left = recursive_keep_minimax(i, k, points, epsilon)
    right = recursive_keep_minimax(k, j, points, epsilon)
    return left + right[1:]

def top_down_split(pc_linear_fx, epsilon):
    """Top-Down Split with Minimax Check"""
    points = pc_linear_fx
    m = len(points)
    if m < 2:
        return points, 0, 0
    given_num_pieces = m - 1
    kept = recursive_keep_minimax(0, m - 1, points, epsilon)
    kept = sorted(set(kept))
    optimal_pc_linear_fx = reconstruct_optimal_points(points, kept, epsilon)
    optimal_num_pieces = len(optimal_pc_linear_fx) - 1 if len(optimal_pc_linear_fx) > 1 else 0
    if len(optimal_pc_linear_fx) != len(kept):
        optimal_pc_linear_fx = points
        optimal_num_pieces = given_num_pieces
    return optimal_pc_linear_fx, optimal_num_pieces, given_num_pieces

def botton_up_merge(pc_linear_fx, epsilon):
    """Bottom-Up Merge with Minimax Check"""
    points = pc_linear_fx
    m = len(points)
    if m < 2:
        return points, 0, 0
    given_num_pieces = m - 1
    kept = list(range(m))
    changed = True
    while changed:
        changed = False
        r = 0
        while r < len(kept) - 2:
            start = kept[r]
            end = kept[r + 2]
            min_E, _, _ = compute_min_E_and_fit(start, end, points)
            if min_E <= epsilon:
                del kept[r + 1]
                changed = True
            else:
                r += 1
    optimal_pc_linear_fx = reconstruct_optimal_points(points, kept, epsilon)
    optimal_num_pieces = len(optimal_pc_linear_fx) - 1 if len(optimal_pc_linear_fx) > 1 else 0
    if len(optimal_pc_linear_fx) != len(kept):
        optimal_pc_linear_fx = points
        optimal_num_pieces = given_num_pieces
    return optimal_pc_linear_fx, optimal_num_pieces, given_num_pieces
