from typing import List, Tuple
import numpy as np
from scipy.optimize import linprog
import heapq
Point = Tuple[float, float]

def _y_on_line(x, x1, y1, x2, y2):
    t = (x - x1) / (x2 - x1)
    return y1 + t * (y2 - y1)
def _feasible_fixed_endpoints(pts: List[Point], i: int, j: int, eps: float) -> bool:
    x1, y1 = pts[i]; x2, y2 = pts[j]
    if x2 == x1:  # should not happen with strictly increasing x
        return False
    for k in range(i + 1, j):
        xk, yk = pts[k]
        yhat = _y_on_line(xk, x1, y1, x2, y2)
        if abs(yk - yhat) > eps:
            return False
    return True
def shortest_path_dp(pc_linear_fx: List[Point], epsilon: float):
    pts = pc_linear_fx
    n = len(pts) - 1
    # Build visibility list nexts[i] = {j>i | segment i->j feasible}
    nexts = [[] for _ in range(n + 1)]
    for i in range(n):
        j = i + 1
        while j <= n and _feasible_fixed_endpoints(pts, i, j, epsilon):
            nexts[i].append(j)
            j += 1

    # Shortest path on DAG
    INF = 10**9
    dp = [INF] * (n + 1)
    prev = [-1] * (n + 1)
    dp[0] = 0
    for i in range(n):
        if dp[i] == INF:
            continue
        for j in nexts[i]:
            if dp[i] + 1 < dp[j]:
                dp[j] = dp[i] + 1
                prev[j] = i

    # Reconstruct
    if dp[n] == INF:
        raise RuntimeError("No feasible simplification within epsilon.")
    idx = []
    cur = n
    while cur != -1:
        idx.append(cur)
        cur = prev[cur]
    idx.reverse()

    optimal_pc = [pts[k] for k in idx]
    optimal_num_pieces = len(optimal_pc) - 1
    given_num_pieces = n
    return optimal_pc, optimal_num_pieces, given_num_pieces



def get_end_interval(i, j, points, epsilon, lo_start, hi_start):
    """
    Compute the feasible interval for y_j' for the segment from i to j,
    with y_i' constrained to [lo_start, hi_start].
    Returns (lo_end, hi_end) or (None, None) if infeasible.
    """
    if i >= j:
        return None, None

    x_list = [p[0] for p in points]
    y_list = [p[1] for p in points]

    dx = x_list[j] - x_list[i]
    if dx == 0:
        return None, None  # degenerate

    num_k = j - i + 1
    num_cons_base = 2 * num_k
    num_cons = num_cons_base + 2  # + bounds on y_start

    A_ub = np.zeros((num_cons, 2))
    b_ub = np.zeros(num_cons)

    cons_idx = 0
    for kk in range(i, j + 1):
        t = 0.0 if kk == i else (x_list[kk] - x_list[i]) / dx
        # upper: (1-t)*y_start + t*y_end <= y_kk + epsilon
        A_ub[cons_idx, 0] = 1 - t
        A_ub[cons_idx, 1] = t
        b_ub[cons_idx] = y_list[kk] + epsilon
        cons_idx += 1
        # lower: -(1-t)*y_start - t*y_end <= -(y_kk - epsilon)
        A_ub[cons_idx, 0] = -(1 - t)
        A_ub[cons_idx, 1] = -t
        b_ub[cons_idx] = -(y_list[kk] - epsilon)
        cons_idx += 1

    # bound y_start <= hi_start
    A_ub[cons_idx, 0] = 1.0
    A_ub[cons_idx, 1] = 0.0
    b_ub[cons_idx] = hi_start
    cons_idx += 1
    # bound -y_start <= -lo_start
    A_ub[cons_idx, 0] = -1.0
    A_ub[cons_idx, 1] = 0.0
    b_ub[cons_idx] = -lo_start

    # Check feasibility
    c_feas = np.array([0.0, 0.0])
    res_feas = linprog(c_feas, A_ub=A_ub, b_ub=b_ub, bounds=(None, None), method='highs')
    if not res_feas.success:
        return None, None

    # Min y_end
    c_min = np.array([0.0, 1.0])
    res_min = linprog(c_min, A_ub=A_ub, b_ub=b_ub, bounds=(None, None), method='highs')
    if not res_min.success:
        return None, None
    lo_end = res_min.fun

    # Max y_end = -min (-y_end)
    c_max = np.array([0.0, -1.0])
    res_max = linprog(c_max, A_ub=A_ub, b_ub=b_ub, bounds=(None, None), method='highs')
    if not res_max.success:
        return None, None
    hi_end = -res_max.fun

    if lo_end > hi_end + 1e-10:  # numerical tolerance
        return None, None

    return lo_end, hi_end

#generated by Grok 4 Fast on 29 Sept 12:40PM
#uses DP LP approach
def fixed_knot_LP(pc_linear_fx, epsilon):
    """
    Computes the optimal piecewise linear approximation with minimal number of pieces
    such that the maximum vertical deviation (infinity norm) is at most epsilon.

    Args:
    pc_linear_fx (list of tuples): List of (x, y) points defining the original piecewise linear function.
                                   Assumes x values are strictly increasing.
    epsilon (float): Tolerance for the infinity norm error.

    Returns:
    tuple: (optimal_pc_linear_fx, optimal_num_pieces, given_num_pieces)
           - optimal_pc_linear_fx: List of (x, y) points for the approximation.
           - optimal_num_pieces: Number of pieces in the approximation.
           - given_num_pieces: Number of pieces in the input.
    """
    points = pc_linear_fx
    m = len(points)
    if m < 2:
        return points, 0, 0

    given_num_pieces = m - 1

    x_list = [p[0] for p in points]
    y_list = [p[1] for p in points]

    INF = float('inf')
    dp = [INF] * m
    prev = [-1] * m
    lo_y = [0.0] * m
    hi_y = [0.0] * m

    dp[0] = 0
    lo_y[0] = y_list[0] - epsilon
    hi_y[0] = y_list[0] + epsilon

    for j in range(1, m):
        min_cost = INF
        union_lo = INF
        union_hi = -INF
        best_prev = -1

        for i in range(j):
            if dp[i] == INF:
                continue
            lo_end, hi_end = get_end_interval(i, j, points, epsilon, lo_y[i], hi_y[i])
            if lo_end is None:
                continue

            new_cost = dp[i] + 1
            if new_cost < min_cost:
                min_cost = new_cost
                union_lo = lo_end
                union_hi = hi_end
                best_prev = i
            elif new_cost == min_cost:
                union_lo = min(union_lo, lo_end)
                union_hi = max(union_hi, hi_end)
                # best_prev remains the same

        if min_cost < INF:
            dp[j] = min_cost
            lo_y[j] = union_lo
            hi_y[j] = union_hi
            prev[j] = best_prev

    optimal_num_pieces = int(dp[m - 1]) if dp[m - 1] < INF else given_num_pieces

    # Reconstruct kept indices
    kept = []
    current = m - 1
    while current >= 0:
        kept.append(current)
        if prev[current] == -1:
            break
        current = prev[current]
    kept.reverse()

    # Now solve global LP for y_primes
    num_kept = len(kept)
    if num_kept == 1:
        # Only one point
        y_prime = [y_list[kept[0]]]  # but adjust? but no segments
        optimal_pc_linear_fx = [(x_list[kept[0]], y_list[kept[0]])]
    else:
        num_pieces = num_kept - 1
        num_constraints = 0
        for r in range(num_pieces):
            a = kept[r]
            b = kept[r + 1]
            num_k = b - a + 1
            num_constraints += 2 * num_k

        A_ub_list = []
        b_ub_list = []

        for r in range(num_pieces):
            a = kept[r]
            b = kept[r + 1]
            dx = x_list[b] - x_list[a]
            if dx == 0:
                # degenerate, but skip or handle
                continue
            for kk in range(a, b + 1):
                t = 0.0 if kk == a else (x_list[kk] - x_list[a]) / dx
                # upper
                row = np.zeros(num_kept)
                row[r] = 1 - t
                row[r + 1] = t
                A_ub_list.append(row)
                b_ub_list.append(y_list[kk] + epsilon)
                # lower
                row = np.zeros(num_kept)
                row[r] = -(1 - t)
                row[r + 1] = -t
                A_ub_list.append(row)
                b_ub_list.append(-(y_list[kk] - epsilon))

        if len(A_ub_list) == 0:
            optimal_pc_linear_fx = [(x_list[idx], y_list[idx]) for idx in kept]
        else:
            A_ub = np.vstack(A_ub_list)
            b_ub = np.array(b_ub_list)
            c = np.zeros(num_kept)
            res = linprog(c, A_ub=A_ub, b_ub=b_ub, bounds=(None, None), method='highs')
            if res.success:
                y_primes = res.x
                optimal_pc_linear_fx = [(x_list[idx], y_primes[p]) for p, idx in enumerate(kept)]
            else:
                # Fallback to original if somehow infeasible
                optimal_pc_linear_fx = points
                optimal_num_pieces = given_num_pieces

    return optimal_pc_linear_fx, optimal_num_pieces, given_num_pieces

def _update_slope_interval(
    x0: float, y0: float, xi: float, yi: float, eps: float,
    smin: float, smax: float
) -> Tuple[float, float, bool]:
    """
    Intersect the current feasible slope interval [smin, smax] with
    the constraint from point (xi, yi): |(y0 + s*(xi-x0)) - yi| <= eps.
    That inequality becomes:
        (yi - y0 - eps)/(xi - x0) <= s <= (yi - y0 + eps)/(xi - x0)
    (Assumes strictly increasing x.)
    Returns updated [smin, smax] and a boolean 'ok' indicating non-empty.
    """
    dx = xi - x0
    # dx should be > 0 because x are strictly increasing for a function
    lo = (yi - y0 - eps) / dx
    hi = (yi - y0 + eps) / dx
    if lo > smin: smin = lo
    if hi < smax: smax = hi
    return smin, smax, (smin <= smax)

def piecewise_linear_apx_furthest_scan(
    pc_linear_fx: List[Point], epsilon: float
) -> Tuple[List[Point], int, int]:
    """
    Exact minimal-piece segmentation under L∞ tolerance with endpoints
    restricted to the given points.

    Returns: (optimal_pc_linear_fx, optimal_num_pieces, given_num_pieces)
    """
    if len(pc_linear_fx) <= 2:
        given_num_pieces = max(0, len(pc_linear_fx) - 1)
        return pc_linear_fx[:], given_num_pieces, given_num_pieces

    xs = [p[0] for p in pc_linear_fx]
    ys = [p[1] for p in pc_linear_fx]
    n = len(xs)

    # Guard: x must be strictly increasing for a valid function
    for k in range(1, n):
        if not (xs[k] > xs[k-1]):
            raise ValueError("x-values must be strictly increasing.")

    out_indices = [0]  # indices of chosen breakpoints; start with first
    i = 0
    while i < n - 1:
        # Start a new segment at i; initialize feasible slope interval unbounded
        smin, smax = float("-inf"), float("inf")
        j = i + 1
        last_ok = i + 1

        # Grow j while feasible
        while j < n:
            smin, smax, ok = _update_slope_interval(xs[i], ys[i], xs[j], ys[j], epsilon, smin, smax)
            if not ok:
                break
            last_ok = j
            j += 1

        # Commit the farthest feasible endpoint
        out_indices.append(last_ok)
        i = last_ok

    # Build output points (use the original sample points as endpoints)
    optimal_pc_linear_fx = [pc_linear_fx[idx] for idx in out_indices]
    optimal_num_pieces = len(optimal_pc_linear_fx) - 1
    given_num_pieces = len(pc_linear_fx) - 1
    return optimal_pc_linear_fx, optimal_num_pieces, given_num_pieces



def _furthest_reach(xs, ys, start, eps):
    """Return all feasible end indices > start for one segment."""
    smin, smax = float("-inf"), float("inf")
    x0, y0 = xs[start], ys[start]
    n = len(xs)
    ends = []
    for j in range(start + 1, n):
        smin, smax, ok = _update_slope_interval(x0, y0, xs[j], ys[j], eps, smin, smax)
        if not ok:
            break
        ends.append(j)
    return ends

def piecewise_linear_apx_beam_search(
    pc_linear_fx: List[Point],
    epsilon: float,
    beam_width: int = 10
) -> Tuple[List[Point], int, int]:
    """
    Beam search piecewise linear approximation under L∞ norm.
    Keeps top 'beam_width' candidate segmentations per frontier.
    """
    n = len(pc_linear_fx)
    if n <= 2:
        given = max(0, n - 1)
        return pc_linear_fx[:], given, given

    xs = [p[0] for p in pc_linear_fx]
    ys = [p[1] for p in pc_linear_fx]

    # Each state = (cost, index, path)
    # cost = segments used so far + heuristic estimate for remaining
    start_state = (0, 0, [0])
    beam = [start_state]

    while True:
        new_beam = []
        for cost, i, path in beam:
            if i == n - 1:
                # Reached end
                return [pc_linear_fx[idx] for idx in path], len(path) - 1, n - 1

            feasible_ends = _furthest_reach(xs, ys, i, epsilon)
            for j in feasible_ends:
                new_cost = cost + 1
                # Heuristic: optimistic segments remaining (approx n-j over avg span)
                heuristic = (n - j - 1) / (len(pc_linear_fx) / 5)
                total_cost = new_cost + heuristic
                new_beam.append((total_cost, j, path + [j]))

        if not new_beam:
            break

        # Keep top-B
        beam = heapq.nsmallest(beam_width, new_beam, key=lambda s: s[0])

    # If somehow we exit without exact end
    best = min(beam, key=lambda s: abs(s[1] - (n - 1)))
    best_path = best[2] + ([n - 1] if best[2][-1] != n - 1 else [])
    return [pc_linear_fx[idx] for idx in best_path], len(best_path) - 1, n - 1





def _triangle_area(p1, p2, p3):
    return abs((p1[0]*(p2[1]-p3[1]) +
                p2[0]*(p3[1]-p1[1]) +
                p3[0]*(p1[1]-p2[1])) / 2.0)

def piecewise_linear_apx_visvalingam(
    pc_linear_fx: List[Tuple[float, float]],
    epsilon: float
) -> Tuple[List[Tuple[float, float]], int, int]:
    """
    Visvalingam–Whyatt simplification. Remove smallest-area points
    until all deviations are within ±epsilon.
    """
    if len(pc_linear_fx) <= 2:
        given = len(pc_linear_fx) - 1
        return pc_linear_fx[:], given, given

    n = len(pc_linear_fx)
    areas = [float('inf')] * n
    heap = []
    for i in range(1, n - 1):
        a = _triangle_area(pc_linear_fx[i - 1], pc_linear_fx[i], pc_linear_fx[i + 1])
        areas[i] = a
        heapq.heappush(heap, (a, i))

    removed = [False] * n
    while heap:
        a, i = heapq.heappop(heap)
        if removed[i]:
            continue
        # Check if within tolerance (approx via area-to-height ratio)
        base = pc_linear_fx[i + 1][0] - pc_linear_fx[i - 1][0]
        height = (2 * a / base) if base != 0 else float('inf')
        if height <= epsilon:
            removed[i] = True
            # Update neighbor triangles
            for j in [i - 1, i + 1]:
                if 0 < j < n - 1 and not removed[j]:
                    new_a = _triangle_area(pc_linear_fx[j - 1], pc_linear_fx[j], pc_linear_fx[j + 1])
                    areas[j] = new_a
                    heapq.heappush(heap, (new_a, j))
        else:
            break

    simplified = [p for i, p in enumerate(pc_linear_fx) if not removed[i]]
    opt = len(simplified) - 1
    given = len(pc_linear_fx) - 1
    return simplified, opt, given
def piecewise_linear_apx_bottom_up_merge(
    pc_linear_fx: List[Tuple[float, float]],
    epsilon: float
) -> Tuple[List[Tuple[float, float]], int, int]:
    """
    Bottom-up merge simplification: iteratively merge neighboring segments
    whose merge causes minimal deviation (under L∞ <= epsilon).
    """
    if len(pc_linear_fx) <= 2:
        given = len(pc_linear_fx) - 1
        return pc_linear_fx[:], given, given

    points = pc_linear_fx[:]
    n = len(points)

    def deviation(i):
        """Compute max |error| if we merge (i, i+1, i+2)."""
        if i < 0 or i + 2 >= len(points):
            return float('inf')
        (x1, y1), (x3, y3) = points[i], points[i + 2]
        max_dev = 0.0
        for k in range(i + 1, i + 2):
            xk, yk = points[k]
            # y on line
            yline = y1 + (y3 - y1) * (xk - x1) / (x3 - x1)
            max_dev = max(max_dev, abs(yk - yline))
        return max_dev

    while True:
        # Find smallest deviation merge
        best_i, best_dev = -1, float('inf')
        for i in range(len(points) - 2):
            d = deviation(i)
            if d < best_dev:
                best_dev, best_i = d, i

        if best_dev > epsilon or best_i == -1:
            break

        # Merge by removing the middle point
        del points[best_i + 1]

    opt = len(points) - 1
    given = len(pc_linear_fx) - 1
    return points, opt, given



