#zero-shot prompt
#generated by GPT-5 model using ChatGPT from my Pro account
#In a new chat
#8 Sept 2025 2:25PM
test_cases = [
    {
        "name": "TC1_constant_function",
        "pc_fx": [
            (-float("inf"), float("inf")),
            (0.0, 1.0),
            (1.0, 1.0),
            (2.0, 1.0),
            (3.0, float("inf")),
        ],
        "epsilon": 0.0,
        "notes": "All segments identical ⇒ optimal should be a single piece when ε=0."
    },
    {
        "name": "TC2_small_jitters_within_2epsilon",
        "pc_fx": [
            (-float("inf"), float("inf")),
            (0.0, 1.00),
            (1.0, 1.05),
            (2.0, 0.98),
            (3.0, 1.02),
            (4.0, 0.99),
            (5.0, float("inf")),
        ],
        "epsilon": 0.06,
        "notes": "All y’s lie within a window < 2ε ⇒ should merge aggressively."
    },
    {
        "name": "TC3_alternating_spikes_hard",
        "pc_fx": [
            (-float("inf"), float("inf")),
            (0.0, 0.0),
            (1.0, 2.0),
            (2.0, 0.0),
            (3.0, 2.0),
            (4.0, 0.0),
            (5.0, float("inf")),
        ],
        "epsilon": 0.4,
        "notes": "Large 2.0 jumps with small ε ⇒ difficult to merge; stresses worst-case segmentation."
    },
    {
        "name": "TC4_single_narrow_outlier",
        "pc_fx": [
            (-float("inf"), float("inf")),
            (0.0, 1.0),
            (1.0, 1.0),
            (2.0, 3.0),   # outlier spike
            (2.1, 1.0),
            (4.0, float("inf")),
        ],
        "epsilon": 0.8,
        "notes": "One tall, very short spike; with ε < (3-1)/2=1 ⇒ spike likely forces an extra piece."
    },
    {
        "name": "TC5_exact_threshold_boundary",
        "pc_fx": [
            (-float("inf"), float("inf")),
            (0.0, 1.0),
            (1.0, 1.8),  # |Δ| = 0.8
            (2.0, 1.0),  # |Δ| = 0.8
            (3.0, float("inf")),
        ],
        "epsilon": 0.4,
        "notes": "Differences exactly 2ε; checks ≤ vs < handling at the merge threshold."
    },
    {
        "name": "TC6_tiny_middle_segment",
        "pc_fx": [
            (-float("inf"), float("inf")),
            (0.0, 2.0),
            (5.0, 2.0),
            (5.001, 1.1),  # tiny island
            (5.002, 2.0),
            (10.0, float("inf")),
        ],
        "epsilon": 0.7,
        "notes": "Vanishingly small central piece; algorithm shouldn’t over-segment just due to short length (L∞)."
    },
    {
        "name": "TC7_fp_noise_near_zero",
        "pc_fx": [
            (-float("inf"), float("inf")),
            (0.0, 0.0),
            (1.0, 1e-12),
            (2.0, -1e-12),
            (3.0, 0.0),
            (4.0, float("inf")),
        ],
        "epsilon": 1e-9,
        "notes": "Floating-point wiggles; ε big enough to ignore numerical noise."
    },
    {
        "name": "TC8_sign_crossing_symmetric",
        "pc_fx": [
            (-float("inf"), float("inf")),
            (0.0, -1.0),
            (1.0, -0.5),
            (2.0, 0.5),
            (3.0, 1.0),
            (4.0, float("inf")),
        ],
        "epsilon": 0.49,
        "notes": "Crosses zero with gaps just above/below ε; tests symmetry and tight merges around 0."
    },
    {
        "name": "TC9_nonuniform_spacing",
        "pc_fx": [
            (-float("inf"), float("inf")),
            (0.0, 0.0),
            (0.001, 0.9),
            (5.0, 0.95),
            (100.0, 1.0),
            (200.0, float("inf")),
        ],
        "epsilon": 0.1,
        "notes": "Very uneven x-spacings; L∞ depends only on y, so spacing shouldn’t affect optimality."
    },
    {
        "name": "TC10_repeated_values_nonadjacent",
        "pc_fx": [
            (-float("inf"), float("inf")),
            (0.0, 2.0),
            (1.0, 0.9),
            (2.0, 2.0),
            (3.0, 1.1),
            (4.0, 2.0),
            (5.0, float("inf")),
        ],
        "epsilon": 0.5,
        "notes": "Same plateau value reappears after deviations; tests whether merges are local & consistent."
    },
]

