#few-shot prompt
#generated by GPT-5 model using ChatGPT from a new account (doesn't have any history of my research problem)
#In a new chat
#8 Sept 2025 3:28PM
#ritamkanabar@gmail.com
# Test cases for piecewise constant approximation under L∞ norm

test_cases = [
    # 1. Constant function (should always be 1 piece regardless of epsilon)
    {
        "pc_fx": [[-float('inf'), float('inf')], [0, 5], [10, 5], [20, float('inf')]],
        "epsilon": 0.1
    },

    # 2. Step function with exact fit within tolerance
    {
        "pc_fx": [[-float('inf'), float('inf')], [0, 2], [5, 4], [10, 2], [15, float('inf')]],
        "epsilon": 2.0
    },

    # 3. Small oscillations (should merge into 1 piece if epsilon is large enough)
    {
        "pc_fx": [[-float('inf'), float('inf')], [0, 1.0], [1, 1.2], [2, 0.9], [3, 1.1], [4, float('inf')]],
        "epsilon": 0.3
    },

    # 4. Large jumps (forces multiple pieces)
    {
        "pc_fx": [[-float('inf'), float('inf')], [0, 0], [1, 10], [2, 0], [3, 10], [4, float('inf')]],
        "epsilon": 4
    },

    # 5. Borderline epsilon (just enough to merge)
    {
        "pc_fx": [[-float('inf'), float('inf')], [0, 0], [1, 1], [2, float('inf')]],
        "epsilon": 1.0
    },

    # 6. Borderline epsilon (just too small, so needs two pieces)
    {
        "pc_fx": [[-float('inf'), float('inf')], [0, 0], [1, 1], [2, float('inf')]],
        "epsilon": 0.9
    },

    # 7. Flat then spike then flat (epsilon decides if spike is ignored)
    {
        "pc_fx": [[-float('inf'), float('inf')], [0, 5], [1, 5], [2, 100], [3, 5], [4, float('inf')]],
        "epsilon": 95
    },

    # 8. Infinite domain with symmetry (check handling of ±inf)
    {
        "pc_fx": [[-float('inf'), float('inf')], [-10, -1], [0, 1], [10, float('inf')]],
        "epsilon": 2
    },

    # 9. Very tight tolerance (forces exact preservation)
    {
        "pc_fx": [[-float('inf'), float('inf')], [0, 0], [1, 0.5], [2, 1.0], [3, float('inf')]],
        "epsilon": 0.01
    },

    # 10. Floating-point boundary values
    {
        "pc_fx": [[-float('inf'), float('inf')], [0, 1.0000001], [1, 1.0000002], [2, float('inf')]],
        "epsilon": 1e-7
    }
]

