#few-shot prompt
#generated by GPT-5 model using ChatGPT from my Pro account
#In a new chat
#11:26pm  7 Sept 2025
#11:26pm  7 Sept 2025

test_cases = [
    {
        "desc": "All values within 2ε ⇒ should merge to 1 piece",
        "pc_fx": [[-float('inf'), float('inf')],
                  [0.0, 2.0], [1.0, 2.4], [2.0, 1.9], [3.0, 2.3], [4.0, 2.1],
                  [5.0, float('inf')]],
        "epsilon": 0.6
    },
    {
        "desc": "Narrow high spike ⇒ spike must be its own piece",
        "pc_fx": [[-float('inf'), float('inf')],
                  [0.0, 2.0], [1.0, 2.0], [2.0, 5.0], [3.0, 2.0], [4.0, 2.0],
                  [5.0, float('inf')]],
        "epsilon": 0.6
    },
    {
        "desc": "Alternating highs/lows just over merge limit ⇒ many pieces",
        "pc_fx": [[-float('inf'), float('inf')],
                  [0.0, 0.0], [1.0, 1.4], [2.0, 0.0], [3.0, 1.4], [4.0, 0.0],
                  [5.0, float('inf')]],
        "epsilon": 0.6
    },
    {
        "desc": "Equality at boundary: max−min = 2ε ⇒ should allow merge",
        "pc_fx": [[-float('inf'), float('inf')],
                  [0.0, 0.0], [1.0, 1.2], [2.0, 0.6], [3.0, 1.2],
                  [4.0, float('inf')]],
        "epsilon": 0.6
    },
    {
        "desc": "Barely over boundary: max−min = 2ε+0.01 ⇒ no merge",
        "pc_fx": [[-float('inf'), float('inf')],
                  [0.0, 0.0], [1.0, 1.21], [2.0, 0.0], [3.0, 1.21],
                  [4.0, float('inf')]],
        "epsilon": 0.6
    },
    {
        "desc": "Tiny boundary blip with amplitude > 2ε ⇒ adds exactly one piece",
        "pc_fx": [[-float('inf'), float('inf')],
                  [0.0, 2.0], [1.0, 2.0], [2.0, 3.6], [3.0, 2.0], [4.0, 2.0],
                  [5.0, float('inf')]],
        "epsilon": 0.6
    },
    {
        "desc": "Negative values with equality at boundary (max−min = 2ε)",
        "pc_fx": [[-float('inf'), float('inf')],
                  [0.0, -1.4], [1.0, -0.2], [2.0, -1.0], [3.0, -0.2],
                  [4.0, float('inf')]],
        "epsilon": 0.6
    },
    {
        "desc": "Large ε ⇒ everything should merge to a single piece",
        "pc_fx": [[-float('inf'), float('inf')],
                  [0.0, -3.0], [1.0, 2.5], [2.0, 7.0], [3.0, -1.0], [4.0, 4.2],
                  [5.0, float('inf')]],
        "epsilon": 10.0
    },
    {
        "desc": "Tiny ε ⇒ effectively no merges unless equal values",
        "pc_fx": [[-float('inf'), float('inf')],
                  [0.0, 0.00], [1.0, 0.03], [2.0, 0.00], [3.0, 0.04], [4.0, 0.01],
                  [5.0, float('inf')]],
        "epsilon": 0.01
    },
    {
        "desc": "Non-consecutive identical levels separated by a high bump",
        "pc_fx": [[-float('inf'), float('inf')],
                  [0.0, 1.0], [1.0, 3.0], [2.0, 1.0], [3.0, 3.0], [4.0, 1.0],
                  [5.0, float('inf')]],
        "epsilon": 0.6
    },
]




