#zero-shot prompt
#generated by GPT-5 model using ChatGPT from a new account (doesn't have any history of my research problem)
#In a new chat
#8 Sept 2:53PM
#riyamkanabar1608@gmail.com
# 10 test cases for piecewise constant approximation algorithm under L∞ norm
# Each test case is (pc_fx, epsilon, description)

test_cases = [
    # 1. Single constant piece (trivial case)
    {
        "pc_fx": [[-float('inf'), float('inf')], [0, 5], [10, float('inf')]],
        "epsilon": 0.1,
        "desc": "Trivial constant function – algorithm should return one piece."
    },

    # 2. Two identical adjacent pieces (should merge)
    {
        "pc_fx": [[-float('inf'), float('inf')], [0, 3], [5, 3], [10, float('inf')]],
        "epsilon": 0.0,
        "desc": "Two adjacent equal values – should be merged into one piece."
    },

    # 3. Small variation within epsilon (should merge)
    {
        "pc_fx" : [[-float('inf'), float('inf')], [0, 3], [5, 3.05], [10, float('inf')]],
        "epsilon": 0.1,
        "desc": "Small jump < epsilon – should be merged."
    },

    # 4. Small variation just above epsilon (should not merge)
    {
        "pc_fx": [[-float('inf'), float('inf')], [0, 3], [5, 3.2], [10, float('inf')]],
        "epsilon": 0.1,
        "desc": "Small jump > epsilon – should stay separate."
    },

    # 5. Increasing staircase (needs multiple pieces)
    {
        "pc_fx": [[-float('inf'), float('inf')],
         [0, 0], [2, 1], [4, 2], [6, 3], [8, 4], [10, float('inf')]],
        "epsilon": 0.5,
        "desc": "Staircase increasing by 1 – algorithm must decide optimal merging."
    },

    # 6. Alternating high/low values (hardest case for merging)
    {
        "pc_fx": [[-float('inf'), float('inf')],
         [0, 0], [1, 10], [2, 0], [3, 10], [4, 0], [5, float('inf')]],
        "epsilon": 4,
        "desc": "Alternating values – algorithm must avoid merging due to large jumps."
    },

    # 7. Long flat with single spike (spike within epsilon)
    {
        "pc_fx": [[-float('inf'), float('inf')],
         [0, 5], [5, 5], [6, 5.05], [7, 5], [10, float('inf')]],
        "epsilon": 0.1,
        "desc": "Single spike within epsilon – spike should be ignored (merge)."
    },

    # 8. Long flat with single spike (spike above epsilon)
    {
        "pc_fx": [[-float('inf'), float('inf')],
         [0, 5], [5, 5], [6, 6], [7, 5], [10, float('inf')]],
        "epsilon": 0.5,
        "desc": "Single spike above epsilon – spike forces an extra piece."
    },

    # 9. Very large epsilon (everything should merge)
    {
        "pc_fx": [[-float('inf'), float('inf')],
         [0, 0], [2, 5], [4, -3], [6, 10], [8, -7], [10, float('inf')]],
        "epsilon": 100,
        "desc": "Huge epsilon – everything merges into one piece."
    },

    # 10. Two far-apart constants (epsilon too small to merge)
    {
        "pc_fx": [[-float('inf'), float('inf')], [0, 0], [10, 100], [20, float('inf')]],
        "epsilon": 10,
        "desc": "Two widely separated values – epsilon too small, must remain 2 pieces."
    },
]
