#few-shot prompt
#generated by GPT-5 model using ChatGPT from my Pro account
#In the same chat where it generated approximation candidate algorithms
#7 Sept 2025 6:35PM
test_cases = [
    # 1) Prompt example, span == 2ε (single segment allowed)
    {
        "pc_fx": [[-float('inf'), float('inf')],[0,2.2],[1,1.6],[2,1.0],[3.0,float('inf')]],
        "epsilon": 0.6,
    },

    # 2) Alternating far jumps (no merges possible)
    {
        "pc_fx": [[-float('inf'), float('inf')],[0,0.0],[1,2.0],[2,0.0],[3,2.0],[4,float('inf')]],
        "epsilon": 0.4,
    },

    # 3) Bowtie chain: pairs feasible, triplet infeasible -> needs 2 segments
    {
        "pc_fx": [[-float('inf'), float('inf')],[0,0.0],[1,0.9],[2,1.8],[3,float('inf')]],
        "epsilon": 0.5,
    },

    # 4) Single spike splits two plateaus -> 3 segments
    {
        "pc_fx": [[-float('inf'), float('inf')],[0,1.0],[1,1.1],[2,2.0],[3,1.0],[4,1.1],[5,float('inf')]],
        "epsilon": 0.3,
    },

    # 5) Huge epsilon merges everything -> 1 segment
    {
        "pc_fx": [[-float('inf'), float('inf')],[0,-7.0],[1,10.0],[2,2.0],[3,15.0],[4,float('inf')]],
        "epsilon": 100.0,
    },

    # 6) ε = 0 (exact matching): merges only equal runs
    {
        "pc_fx": [[-float('inf'), float('inf')],[0,1],[1,1],[2,2],[3,2],[4,1],[5,1],[6,float('inf')]],
        "epsilon": 0.0,
    },

    # 7) Hairline over-threshold split (floating precision edge)
    {
        "pc_fx": [[-float('inf'), float('inf')],[0,0.0],[1,1.0],[2,2.0000000001],[3,float('inf')]],
        "epsilon": 0.5,
    },

    # 8) Gentle drift all within ε -> 1 segment
    {
        "pc_fx": [[-float('inf'), float('inf')],[0,0.0],[1,0.3],[2,0.6],[3,0.9],[4,float('inf')]],
        "epsilon": 0.6,
    },

    # 9) Staircase: pairs feasible, entire span not -> 2 segments
    {
        "pc_fx": [[-float('inf'), float('inf')],[0,0.0],[1,0.9],[2,1.8],[3,2.7],[4,float('inf')]],
        "epsilon": 0.49,
    },

    # 10) Symmetric hump -> minimal 3 segments
    {
        "pc_fx": [[-float('inf'), float('inf')],[0,0.0],[1,1.0],[2,2.0],[3,1.0],[4,0.0],[5,float('inf')]],
        "epsilon": 0.5,
    },
]
